<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Zone;

class ZoneSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // อาคารวิทยบริการ A (loc_id=1)
            [
                'pic'              => 'a.jpg',
                'loc_id'           => 1,
                'title'            => 'ห้องเรียนรู้ A (ชั้น 4)',
                'title_eng'        => 'Study Room A (4 floor)',
                'detail'           => 'ห้องประชุมกลุ่มขนาดเล็ก เหมาะสำหรับทำงานร่วมกัน นำเสนองาน และศึกษากลุ่ม',
                'capacity'         => '2-6 คน',
                'tool'             => 'โต๊ะประชุม, เก้าอี้, กระดานไวท์บอร์ด, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'b.jpg',
                'loc_id'           => 1,
                'title'            => 'ห้องเรียนรู้ B (ชั้น 4)',
                'title_eng'        => 'Study Room B (4 floor)',
                'detail'           => 'ห้องนำเสนองานพร้อม Smart TV เหมาะสำหรับประชุมกลุ่ม อภิปราย และนำเสนอสไลด์',
                'capacity'         => '1-4 คน',
                'tool'             => 'Smart TV, โต๊ะ, เก้าอี้, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'c.jpg',
                'loc_id'           => 1,
                'title'            => 'ห้องเรียนรู้ C (ชั้น 4)',
                'title_eng'        => 'Study Room C (4 floor)',
                'detail'           => 'ห้องอบรมขนาดใหญ่ รองรับผู้เข้าร่วมได้สูงสุด 4 คน พร้อม Smart TV และปลั๊กไฟครบจุด',
                'capacity'         => '1-4 คน',
                'tool'             => 'Smart TV, โต๊ะ, เก้าอี้, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'pavilion.jpg',
                'loc_id'           => 1,
                'title'            => 'PAVILION ROOM (ชั้น 3)',
                'title_eng'        => 'PAVILION ROOM (3 floor)',
                'detail'           => 'บูธส่วนตัวแบบ Semi-open เหมาะสำหรับอ่านหนังสือและทบทวนตำรา มีปลั๊กและ LAN',
                'capacity'         => '1-2 คน',
                'tool'             => 'โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'nap.jpg',
                'loc_id'           => 1,
                'title'            => 'NAP Zone (ชั้น 3)',
                'title_eng'        => 'NAP Zone (3 floor)',
                'detail'           => 'พื้นที่พักผ่อนส่วนตัว สภาพแวดล้อมเงียบสงบ เหมาะสำหรับงีบหลับระหว่างวัน',
                'capacity'         => '1 คน',
                'tool'             => 'Wi-Fi',
                'min_capacity'     => 1,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'comp.jpg',
                'loc_id'           => 1,
                'title'            => 'Computer Zone (ชั้น 3)',
                'title_eng'        => 'Computer Zone (3 floor)',
                'detail'           => 'บูธคอมพิวเตอร์ส่วนตัว สำหรับสืบค้นฐานข้อมูลและทรัพยากรสารสนเทศของห้องสมุด',
                'capacity'         => '1 คน',
                'tool'             => 'Computer, โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'chair.jpg',
                'loc_id'           => 1,
                'title'            => 'Chair Zone (ชั้น 3)',
                'title_eng'        => 'Chair Zone (3 floor)',
                'detail'           => 'พื้นที่นั่งพักผ่อนส่วนตัว เหมาะสำหรับอ่านหนังสือหรือผ่อนคลายระหว่างวัน',
                'capacity'         => '1 คน',
                'tool'             => 'เก้าอี้นั่งสบาย, Wi-Fi',
                'min_capacity'     => 1,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'pg.jpg',
                'loc_id'           => 1,
                'title'            => 'PLAYGROUND (ชั้น 1)',
                'title_eng'        => 'PLAYGROUND (1 floor)',
                'detail'           => 'พื้นที่กิจกรรมขนาดใหญ่ มีกระจกบานใหญ่ เหมาะสำหรับ Cover Dance ซ้อมการแสดง และกิจกรรมกลุ่ม',
                'capacity'         => '5 คนขึ้นไป',
                'tool'             => 'Wi-Fi, กระจก, เครื่องปรับอากาศ',
                'min_capacity'     => 3,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            // DLP
            [
                'pic'              => 'std.jpg',
                'loc_id'           => 2,
                'title'            => 'Study Room (ชั้น 2)',
                'title_eng'        => 'Study Room (2 floor)',
                'detail'           => 'ห้องศึกษากลุ่มขนาดกลาง มี TV และโซฟา เหมาะสำหรับอภิปรายและทำงานร่วมกัน',
                'capacity'         => '2-6 คน',
                'tool'             => 'TV, Wi-Fi, โซฟา',
                'min_capacity'     => 2,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'tv.jpg',
                'loc_id'           => 2,
                'title'            => 'ทีวีออนไลน์เพื่อการศึกษา (ชั้น 2)',
                'title_eng'        => 'Smart Television (2 floor)',
                'detail'           => 'ห้องรับชมสื่อการศึกษาออนไลน์ พร้อม Smart TV และโซฟานั่งสบาย',
                'capacity'         => '2-4 คน',
                'tool'             => 'TV, Wi-Fi, โซฟา',
                'min_capacity'     => 2,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'computer.jpg',
                'loc_id'           => 2,
                'title'            => 'Computer Zone (ชั้น 2)',
                'title_eng'        => 'Computer Zone (2 floor)',
                'detail'           => 'บูธคอมพิวเตอร์ส่วนตัว สำหรับสืบค้นฐานข้อมูลและทรัพยากรสารสนเทศของห้องสมุด',
                'capacity'         => '1 คน',
                'tool'             => 'Computer, โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'gameplay.jpg',
                'loc_id'           => 2,
                'title'            => 'Game Playstation (ชั้น 2)',
                'title_eng'        => 'Game Playstation (2 floor)',
                'detail'           => 'บูธเกม PlayStation สำหรับเล่นร่วมกัน พร้อมจอยคอนโทรลเลอร์และโซฟานั่งสบาย',
                'capacity'         => '2-4 คน',
                'tool'             => 'PlayStation 5, จอยคอนโทรลเลอร์, โซฟา, Wi-Fi',
                'min_capacity'     => 2,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'gameonline.jpg',
                'loc_id'           => 2,
                'title'            => 'Game Online (ชั้น 2)',
                'title_eng'        => 'Game Online (2 floor)',
                'detail'           => 'บูธเกมออนไลน์ส่วนตัว สเปกสูง พร้อมหูฟัง เหมาะสำหรับเล่นเกมและรับชมสื่อมัลติมีเดีย',
                'capacity'         => '1 คน',
                'tool'             => 'Computer, โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'pool.jpg',
                'loc_id'           => 2,
                'title'            => 'Pool Table (ชั้น 2)',
                'title_eng'        => 'Pool Table (2 floor)',
                'detail'           => 'พื้นที่เล่นสนุ๊กและพูลมาตรฐาน พร้อมโต๊ะและอุปกรณ์ครบชุด',
                'capacity'         => '2-4 คน',
                'tool'             => 'โต๊ะพูล, ไม้สนุ๊ก',
                'min_capacity'     => 2,
                'zone_daily_quota' => 3,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
            [
                'pic'              => 'libspace.jpg',
                'loc_id'           => 2,
                'title'            => 'Library Space (ชั้น 2)',
                'title_eng'        => 'Library Space (2 floor)',
                'detail'           => 'พื้นที่ผ่อนคลายอเนกประสงค์ รองรับการร้องคาราโอเกะ รับชมสื่อออนไลน์ และกิจกรรมบันเทิง',
                'capacity'         => '2-4 คน',
                'tool'             => 'ระบบคาราโอเกะ, จอแสดงเนื้อเพลง, Computer, เก้าอี้, Wi-Fi',
                'min_capacity'     => 2,
                'zone_daily_quota' => 1,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '0',
            ],
        ];

        foreach ($data as $r) {
            Zone::updateOrCreate(
                ['title' => $r['title'], 'loc_id' => $r['loc_id']],
                [
                    'pic'              => $r['pic'],
                    'title_eng'        => $r['title_eng'],
                    'detail'           => $r['detail'],
                    'capacity'         => $r['capacity'],
                    'tool'             => $r['tool'],
                    'min_capacity'     => $r['min_capacity'],
                    'zone_daily_quota' => $r['zone_daily_quota'],
                    'time_weekday'     => $r['time_weekday'],
                    'time_weekend'     => $r['time_weekend'],
                    'status'           => $r['status'],
                ]
            );
        }
    }
}
