<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Zone;

class ZoneSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // อาคารวิทยบริการ A (loc_id=1)
            [
                'pic'              => 'a.jpg',
                'loc_id'           => 1,
                'title'            => 'ห้องเรียนรู้ A (ชั้น 4)',
                'title_eng'        => 'Study Room A (4 floor)',
                'detail'           => 'พื้นที่สำหรับอ่านหนังสือ งานนำเสนอ และจัดประชุมขนาดเล็ก',
                'capacity'         => '2-6 คน',
                'tool'             => 'โต๊ะ, เก้าอี้, Wi-Fi',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'b.jpg',
                'loc_id'           => 1,
                'title'            => 'ห้องเรียนรู้ B (ชั้น 4)',
                'title_eng'        => 'Study Room B (4 floor)',
                'detail'           => 'พื้นที่สำหรับอ่านหนังสือ งานนำเสนอ และจัดประชุมขนาดเล็ก',
                'capacity'         => '1-4 คน',
                'tool'             => 'Smart TV, โต๊ะ, เก้าอี้, Wi-Fi',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'c.jpg',
                'loc_id'           => 1,
                'title'            => 'ห้องเรียนรู้ C (ชั้น 4)',
                'title_eng'        => 'Study Room C (4 floor)',
                'detail'           => 'พื้นที่ขนาดใหญ่ สำหรับงานอบรม งานนำเสนอ และจัดประชุม',
                'capacity'         => '1-4 คน',
                'tool'             => 'Smart TV, โต๊ะ, เก้าอี้, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'pavilion.jpg',
                'loc_id'           => 1,
                'title'            => 'PAVILION ROOM (ชั้น 3)',
                'title_eng'        => 'PAVILION ROOM (3 floor)',
                'detail'           => 'พื้นที่ส่วนตัวสำหรับอ่านหนังสือ ทบทวนตำรา',
                'capacity'         => '1-2 คน',
                'tool'             => 'โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'nap.jpg',
                'loc_id'           => 1,
                'title'            => 'NAP Zone (ชั้น 3)',
                'title_eng'        => 'NAP Zone (3 floor)',
                'detail'           => 'พื้นที่ส่วนตัวสำหรับพักผ่อน งีบหลับ',
                'capacity'         => '1 คน',
                'tool'             => 'Wi-Fi',
                'min_capacity'     => 1,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'comp.jpg',
                'loc_id'           => 1,
                'title'            => 'Computer Zone (ชั้น 3)',
                'title_eng'        => 'Computer Zone (3 floor)',
                'detail'           => 'พื้นที่ส่วนตัวสำหรับสืบค้นทรัพยากรสารสนเทศ',
                'capacity'         => '1 คน',
                'tool'             => 'Computer, โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'pg.jpg',
                'loc_id'           => 1,
                'title'            => 'PLAYGROUND (ชั้น 1)',
                'title_eng'        => 'PLAYGROUND (1 floor)',
                'detail'           => 'พื้นที่ขนาดใหญ่ สำหรับ Cover Dance, ซ้อมการแสดง',
                'capacity'         => '5 คนขึ้นไป',
                'tool'             => 'Wi-Fi, กระจก, เครื่องปรับอากาศ',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            // DLP
            [
                'pic'              => 'std.jpg',
                'loc_id'           => 2,
                'title'            => 'Study Room (ชั้น 2)',
                'title_eng'        => 'Study Room (2 floor)',
                'detail'           => 'พื้นที่ขนาดกลาง สำหรับรับชมสื่อออนไลน์',
                'capacity'         => '2-6 คน',
                'tool'             => 'TV, Wi-Fi, โซฟา',
                'min_capacity'     => 2,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'tv.jpg',
                'loc_id'           => 2,
                'title'            => 'ทีวีออนไลน์เพื่อการศึกษา (ชั้น 2)',
                'title_eng'        => 'Smart Television (2 floor)',
                'detail'           => 'พื้นที่ขนาดกลาง สำหรับรับชมสื่อออนไลน์',
                'capacity'         => '2-4 คน',
                'tool'             => 'TV, Wi-Fi, โซฟา',
                'min_capacity'     => 2,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'computer.jpg',
                'loc_id'           => 2,
                'title'            => 'Computer Zone (ชั้น 2)',
                'title_eng'        => 'Computer Zone (2 floor)',
                'detail'           => 'พื้นที่ส่วนตัวสำหรับสืบค้นทรัพยากรสารสนเทศ',
                'capacity'         => '1 คน',
                'tool'             => 'Computer, โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'gameplay.jpg',
                'loc_id'           => 2,
                'title'            => 'Game Playstation (ชั้น 2)',
                'title_eng'        => 'Game Playstation (2 floor)',
                'detail'           => 'พื้นที่สำหรับเล่นเกมส์ Playstation และสื่อมัลติมีเดีย',
                'capacity'         => '2-4 คน',
                'tool'             => 'เกมส์, โซฟา',
                'min_capacity'     => 2,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'gameonline.jpg',
                'loc_id'           => 2,
                'title'            => 'Game Online (ชั้น 2)',
                'title_eng'        => 'Game Online (2 floor)',
                'detail'           => 'พื้นที่สำหรับเล่นเกมส์ออนไลน์ และรับชมสื่อมัลติมีเดีย',
                'capacity'         => '1 คน',
                'tool'             => 'Computer, โต๊ะ, เก้าอี้, Wi-Fi, LAN, ปลั๊กไฟ',
                'min_capacity'     => 1,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'pool.jpg',
                'loc_id'           => 2,
                'title'            => 'Pool Table (ชั้น 2)',
                'title_eng'        => 'Pool Table (2 floor)',
                'detail'           => 'พื้นที่สำหรับเล่นสนุ๊ก เล่นพูล',
                'capacity'         => '2-4 คน',
                'tool'             => 'โต๊ะพูล, ไม้สนุ๊ก',
                'min_capacity'     => 2,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'libspace.jpg',
                'loc_id'           => 2,
                'title'            => 'Library Space (ชั้น 2)',
                'title_eng'        => 'Library Space (2 floor)',
                'detail'           => 'พื้นที่สำหรับผ่อนคลาย รับชมสื่อออนไลน์ ร้องคาราโอเกะ',
                'capacity'         => '2-4 คน',
                'tool'             => 'Computer, เก้าอี้',
                'min_capacity'     => 2,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            // MSU Space
            [
                'pic'              => 'room_1.jpg',
                'loc_id'           => 3,
                'title'            => 'ห้องประชุม 1 (ชั้น 2)',
                'title_eng'        => 'Meeting Room 1 (2 floor)',
                'detail'           => 'พื้นที่ขนาดใหญ่ สำหรับงานอบรม งานนำเสนอ และจัดประชุมเฉพาะคณะ/หน่วยงาน',
                'capacity'         => '5 คนขึ้นไป',
                'tool'             => 'Smart TV, เครื่องเสียง, ไมค์, โต๊ะ, เก้าอี้, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'room_2.jpg',
                'loc_id'           => 3,
                'title'            => 'ห้องประชุม 2 (ชั้น 2)',
                'title_eng'        => 'Meeting Room 2 (2 floor)',
                'detail'           => 'พื้นที่ขนาดใหญ่ สำหรับงานอบรม งานนำเสนอ และจัดประชุมเฉพาะคณะ/หน่วยงาน',
                'capacity'         => '5 คนขึ้นไป',
                'tool'             => 'Smart TV, เครื่องเสียง, ไมค์, โต๊ะ, เก้าอี้, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
            [
                'pic'              => 'room_3.jpg',
                'loc_id'           => 3,
                'title'            => 'ห้องประชุม 3 (ชั้น 2)',
                'title_eng'        => 'Meeting Room 3 (2 floor)',
                'detail'           => 'พื้นที่ขนาดใหญ่ สำหรับงานอบรม งานนำเสนอ และจัดประชุมเฉพาะคณะ/หน่วยงาน',
                'capacity'         => '5 คนขึ้นไป',
                'tool'             => 'Smart TV, เครื่องเสียง, ไมค์, โต๊ะ, เก้าอี้, Wi-Fi, ปลั๊กไฟ',
                'min_capacity'     => 3,
                'zone_daily_quota' => null,
                'time_weekday'     => 1,
                'time_weekend'     => 4,
                'status'           => '1',
            ],
        ];

        foreach ($data as $r) {
            Zone::updateOrCreate(
                ['title' => $r['title'], 'loc_id' => $r['loc_id']],
                [
                    'pic'              => $r['pic'],
                    'title_eng'        => $r['title_eng'],
                    'detail'           => $r['detail'],
                    'capacity'         => $r['capacity'],
                    'tool'             => $r['tool'],
                    'min_capacity'     => $r['min_capacity'],
                    'zone_daily_quota' => $r['zone_daily_quota'],
                    'time_weekday'     => $r['time_weekday'],
                    'time_weekend'     => $r['time_weekend'],
                    'status'           => $r['status'],
                ]
            );
        }
    }
}
